name: Feature Request
description: Suggest an idea for this project
title: "[feature name]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
      placeholder: Describe the feature you are requesting
      render: markdown
  - type: dropdown
    id: typeOfFeature
    attributes:
      label: Type of Feature
      description: What type of feature is this?
      multiple: true
      options:
        - Frontend
        - Backend
        - Fullstack
    validations:
      required: true
